### ISSUE TITLE
Begin equation returns object to the AST

### ISSUE THREAD

**Issue by rowanc1** [siefkenj/latex-parser#18]
Super cool library! I was looking at the playground and found that the equation environment is doing something weird? It seems to format ok, but the AST is incorrect, which is probably why the HTML output doesn't work:

![image](https://user-images.githubusercontent.com/913249/153719912-b2c69bd5-db8f-4632-9fc8-6c6f7d4b0476.png)

![image](https://user-images.githubusercontent.com/913249/153719933-b1e7713b-5382-466c-b37c-8c87e50d8414.png)

**Comment by siefkenj** [comment]
Ah, I see the error. The display code things `equation` is a string, but actually the environment label is another AST. If you look at the JSON AST view, you should see it correctly.

The HTML view is a little weird because KaTeX only recognizes math in `$...$`. If you wrap your `\begin{equation}` in `$...$`, it should work (even though it is invalid LaTeX code!). I'm not sure what the best solution is, because apparently MathJax has the opposite behavior.

**Comment by rowanc1** [comment]
Nice, so parse is fine, just looking at the "AST" view. In other serializers for math I have seen them write out the html in the walk or directly visit the nodes in a tree. I have always found that the katex api is easier to understand in node:
https://katex.org/docs/api.html

I am sure you can do this in mathjax as well, maybe this would help:
https://github.com/remarkjs/remark-math

I am currently doing some work to standardize parsing of a markdown flavour, [myst](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html), on [mdast](https://github.com/syntax-tree/mdast) which then allows entry into all of the plugins in the [unified](https://unifiedjs.com/learn/) world.

It would be really cool to see this latex parser's ast be similar in structure, I think the major change is renaming your content lists to `children` and then you can start to take advantage of all sorts of unit-utils to transform the AST. As well as the serializers out to HTML, etc.

Happy to explain more if this is something you might be interested in!

**Comment by siefkenj** [comment]
I just discovered unified a little while ago and was thinking of incorporating it. As I understand it, the only required attribute for the AST is `type` which `latex-parser` already has.

Currently the HTML conversion is a nasty hack. Since a macro has an `escapeToken` and `content` and `arguments`, and each argument has an `openMark` and `closeMark`, I create a macro with empty `content` and `escapeToken` and then create arguments with `openMark="<tag>"` and `closeMark="</tag>"`. Then the default printer will print out HTML. It would be much nicer to convert to HAST or some such.

I don't like the idea of renaming `content` so much...one of my goals with the AST is to have it as uniform as possible. So, a comment has `content` and a macro has `content` and an environment has `content`. But, philosophically, a comment doesn't have `children`, and if a macro has children, it should be its argument, which means that a macro would need a `macroName` or something like that. This would cascade and cause lots of changes.

**Comment by rowanc1** [comment]
I think that for the traversal codes to work you need `children` defined. This is what [`unist-builder`](https://github.com/syntax-tree/unist-builder) and mdast use at least. The `unist-util-visit`/select/map are all really handy and work with the `children` list. With those defined you can start to do selections and transformations of the AST or expose those to downstream consumers of the ast.

Fair point about the uniform content idea. In mdast/hast they have gone a different way, making it clear what is a leaf or a parent in the tree (rather than a `type content === 'string'` check or similar?).

How I have been doing my export is taking my custom tree and then transforming it for export to other formats (e.g. going from specific latex => mdast => html). It would be really cool to have some interop between latex and myst, currently it is only one way (myst==> latex) but potentially joining up with your ast could change that! :)

**Comment by siefkenj** [comment]
@rowanc1 If you look at PR #22 I have started to refactor the code to fit with the `unifiedjs` framework.

**Comment by rowanc1** [comment]
So cool!

**Comment by siefkenj** [comment]
@rowanc1 I have ported the `unified-latex` functions to their own repository https://github.com/siefkenj/unified-latex and fixed the AST to now return `environment.env` as a string instead of a node list. This fixes the error in the playground :-)

**Comment by rowanc1** [comment]
Following up on this now! Super cool to see you have moved into unified, already seeing this pop up in other unified repos! I will keep tabs on the new project!
